import json
import os
import datetime as dt
from pathlib import Path
from typing import Any

import requests

MARKET_DATA_PATH = Path(os.environ.get('MARKET_DATA_PATH', 'market_data.json'))
PDF_PATH = Path(os.environ.get('PDF_PATH', 'report.pdf'))
BRANCH = os.environ.get('GITHUB_REF_NAME', 'main')
REPOSITORY = os.environ.get('GITHUB_REPOSITORY', '')
RUN_ID = os.environ.get('GITHUB_RUN_ID', '')
RUN_NUMBER = os.environ.get('GITHUB_RUN_NUMBER', '')


def must_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise SystemExit(f'Missing required environment variable: {name}')
    return value.rstrip('/') if name == 'SUPABASE_URL' else value


def headers(service_key: str) -> dict[str, str]:
    return {
        'apikey': service_key,
        'Authorization': f'Bearer {service_key}',
        'Content-Type': 'application/json',
        'Prefer': 'resolution=merge-duplicates,return=representation',
    }


def iso_report_date(data: dict[str, Any]) -> str:
    # Prefer market data date, because the report should match the data snapshot date.
    for key in ('market_as_of_date', 'report_date'):
        value = data.get(key)
        if isinstance(value, str) and len(value) >= 10:
            try:
                return dt.datetime.strptime(value[:10], '%Y-%m-%d').date().isoformat()
            except Exception:
                pass

    cfg_date = (data.get('config') or {}).get('report_date')
    if isinstance(cfg_date, str):
        for fmt in ('%d %B %Y', '%Y-%m-%d'):
            try:
                return dt.datetime.strptime(cfg_date, fmt).date().isoformat()
            except Exception:
                pass

    return dt.date.today().isoformat()


def raw_github_url(filename: str) -> str:
    if not REPOSITORY:
        return filename
    # Cache buster avoids dashboard opening an older browser-cached PDF/JSON.
    suffix = f'?run={RUN_ID}' if RUN_ID else ''
    return f'https://raw.githubusercontent.com/{REPOSITORY}/{BRANCH}/{filename}{suffix}'


def dashboard_status(report_status: str) -> str:
    status = (report_status or '').upper()
    if status in {'PASS', 'OK'}:
        return 'draft'
    if status in {'FAIL', 'FAILED'}:
        return 'needs_review'
    return 'needs_review'


def main() -> int:
    supabase_url = must_env('SUPABASE_URL')
    service_key = must_env('SUPABASE_SERVICE_ROLE_KEY')

    if not MARKET_DATA_PATH.exists():
        raise SystemExit(f'{MARKET_DATA_PATH} not found. Cannot register report.')
    if not PDF_PATH.exists():
        raise SystemExit(f'{PDF_PATH} not found. Cannot register report.')

    with MARKET_DATA_PATH.open('r', encoding='utf-8') as f:
        data = json.load(f)

    report_status = str(data.get('report_status') or 'UNKNOWN').upper()
    issues = data.get('validation_issues') or []
    report_date = iso_report_date(data)
    generated_at = dt.datetime.now(dt.timezone.utc).isoformat()

    record = {
        'report_date': report_date,
        'status': dashboard_status(report_status),
        'validation_status': report_status,
        'validation_issues': issues,
        'email_send_allowed': False,
        'generated_at': generated_at,
        'approved_by': None,
        'approved_at': None,
        'pdf_url': raw_github_url('report.pdf'),
        'market_data_url': raw_github_url('market_data.json'),
        'github_run_id': RUN_ID,
        'github_run_number': RUN_NUMBER,
        'notes': 'Generated by GitHub Actions. Awaiting human review and dashboard approval.'
    }

    url = f'{supabase_url}/rest/v1/reports?on_conflict=report_date'
    resp = requests.post(url, headers=headers(service_key), json=record, timeout=30)

    if resp.status_code not in (200, 201):
        print('Supabase reports upsert failed')
        print(resp.status_code)
        print(resp.text)
        raise SystemExit(1)

    print(f'Report registered in Supabase reports table: {report_date} | validation={report_status} | status={record["status"]}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
